//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dan_LIII_Milos_Peric
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwManager
    {
        public int UserID { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int ManagerID { get; set; }
        public Nullable<int> FloorNumber { get; set; }
        public Nullable<int> WorkExperience { get; set; }
        public string LevelOfEducation { get; set; }
    }
}
